"""A tiny, self‑contained example that Jules created on its first run.

Running this script prints a friendly greeting.  Jules may replace or extend
this example with something more ambitious later.
"""


def main() -> None:
    print("Hello, world! (generated by Jules)")


if __name__ == "__main__":
    main()
